# .travis.yml
#
# Setup for travis-cl.com
#
# @category  None
# @package   /
# @author    Rick Morice <rick@floor9design.com>
# @copyright Floor9design Ltd (floor9design.com)
# @license   MIT
# @version   1.4
# @link      https://floor9design.com
# @see       https://floor9design.com
# @since     File available since Release 1.0
language: php
dist: jammy
php:
  - '8.1'

env:
  - XDEBUG_MODE=coverage

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - ./vendor/phpunit/phpunit/phpunit --coverage-clover coverage.xml

after_success:
  #- curl -Os https://uploader.codecov.io/latest/linux/codecov
  #- chmod +x codecov
  #- ./codecov
  - bash <(curl -s https://codecov.io/bash)


