language: php

php:
  - '8.0'
  - '7.4'
  - '7.3'

env:
  - XDEBUG_MODE=coverage

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - ./vendor/phpunit/phpunit/phpunit --coverage-html docs/tests/
  - ./vendor/phpunit/phpunit/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)


